### ISSUE TITLE
Lesson 12: Matrix Job issue

### ISSUE THREAD

**Issue by DeclanRodgers** [cschleiden/github-actions-hero#41]
I'm new to learning Github Actions. For this lesson, I put in what I thought was the correct answer:

``` yaml
 matrix:
        version: [8, 10, 12]
        component: [frontend, backend]
```
![image](https://user-images.githubusercontent.com/107404809/215437458-8c880def-c5ab-4bb3-a4d7-5abe6ac0538f.png)

I don't get an error, but it doesn't let me proceed. I had a look through the source and can see the result must contain "frontend" and "backend".
